uses: Platane/snk@latest
with:
  github_user_name: ${{ github.repository_owner }}
  svg_out_path: dist/github-contribution-grid-snake.svg

uses: crazy-max/ghaction-github-pages@latest
with:
  target_branch: output
  build_dir: dist
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
